MyGraduationProject/Controllers/AdminsController.cs
using DatabaseAccess;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using MyGraduationProject.Models;
using MyGraduationProject.Models.Enums;
using PagedList;

namespace MyGraduationProject.Controllers
{
    public class AdminsController : Controller
    {
        //zmienna bezpośredniego dostępu do bazy danych
        private DataClassesDataContext db = new DataClassesDataContext();

        //zmienna dostępu do klasy MyRepository
        private MyRepository repo = new MyRepository();

        //widok o nazwie Index z folderu Admins wyświetli liste wszystkich użytkowników
        // GET: Admins
        public ActionResult Index(string sorting , string filtrationLogin, int? page)
        {
            ViewBag.Auth = null;
            if (Session["principal"] != null)
            {
                ViewBag.Auth = (User)(Session["principal"]);
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    ViewBag.SortedBy = sorting;
                    ViewBag.SortByNAME = sorting == null ? "NAME_Malejaco" : "";
                    ViewBag.SortBySURNAME = sorting == "SURNAME_Malejaco" ? "SURNAME_Rosnaco" : "SURNAME_Malejaco";

                    var users = repo.GetAllUsers();

                    if (ModelState.IsValid)
                    {
                        if (filtrationLogin != null && filtrationLogin != "")
                        {
                            users = users.Where(u => u.LOGIN.Contains(filtrationLogin));
                        }

                        ViewBag.FindLogin = filtrationLogin;
                    

                        switch (sorting)
                        {
                            case "NAME_Malejaco":
                                users = users.OrderByDescending(s => s.NAME);
                                break;
                            case "SURNAME_Malejaco":
                                users = users.OrderByDescending(s => s.SURNAME);
                                break;
                            case "SURNAME_Rosnaco":
                                users = users.OrderBy(s => s.SURNAME);
                                break;
                            default:
                                users = users.OrderBy(s => s.NAME);
                                break;
                        }

                        int pageSize = 5;
                        int pageNumber = (page ?? 1);
                        return View(users.ToPagedList(pageNumber, pageSize));
                    }
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Admins/Create
        public ActionResult Create()
        {
            ViewBag.Auth = null;
            if (Session["principal"] != null)
            {
                ViewBag.Auth = (User)(Session["principal"]);
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    ViewBag.ROLE_ID = new SelectList(repo.GetAllRoles(), "ROLE_ID", "NAME");
                    return View();
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Admins/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User user)
        {
            ViewBag.Auth = null;
            if (Session["principal"] != null)
            {
                ViewBag.Auth = (User)(Session["principal"]);
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    if (ModelState.IsValid)
                    {
                        //sprawdzamy czy podany login nie jest zajęty
                        var validation = repo.FreeLoginConfirm(user.LOGIN);
                        if (validation == false)
                        {
                            db.Users.InsertOnSubmit(user);
                            db.SubmitChanges();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ModelState.AddModelError("", "Ten login jest juz zajęty");
                        }
                    }

                    ViewBag.ROLE_ID = new SelectList(repo.GetAllRoles(), "ROLE_ID", "NAME", user.ROLE_ID);
                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Admins/Edit/5
        public ActionResult Edit(int? id)
        {

            ViewBag.Auth = null;
            if (Session["principal"] != null)
            {
                ViewBag.Auth = (User)(Session["principal"]);
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }
                    var user = repo.GetUserById((int)id);
                    if (user == null)
                    {
                        return HttpNotFound();
                    }
                    ViewBag.ROLE_ID = new SelectList(repo.GetAllRoles(), "ROLE_ID", "NAME", user.ROLE_ID);
                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Admins/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User user)
        {
            ViewBag.Auth = null;
            if (Session["principal"] != null)
            {
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    if (ModelState.IsValid)
                    {
                        
                        var userToEdit = db.Users.Where(u => u.USER_ID == user.USER_ID).FirstOrDefault();

                            userToEdit.LOGIN = user.LOGIN;
                            userToEdit.PASSWORD = user.PASSWORD;
                            userToEdit.NAME = user.NAME;
                            userToEdit.SURNAME = user.SURNAME;
                            userToEdit.PESEL = user.PESEL;
                            userToEdit.UsersAdress.STREET_NAME = user.UsersAdress.STREET_NAME;
                            userToEdit.UsersAdress.STREET_NUMBER = user.UsersAdress.STREET_NUMBER;
                            userToEdit.UsersAdress.POSSESION_NUMBER = user.UsersAdress.POSSESION_NUMBER;
                            userToEdit.ROLE_ID = user.ROLE_ID;
                            db.SubmitChanges();

                        if (current.USER_ID == userToEdit.USER_ID)
                        {
                            Session["principal"] = userToEdit;
                        }
                        ViewBag.Auth = (User)(Session["principal"]);
                        return RedirectToAction("Index");
                    }
                    ViewBag.ROLE_ID = new SelectList(repo.GetAllRoles(), "ROLE_ID", "NAME", user.ROLE_ID);
                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: Admins/Delete/5
        public ActionResult Delete(int? id)
        {
            if (Session["principal"] != null)
            {
                ViewBag.Auth = (User)(Session["principal"]);
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    if (id == null)
                    {
                        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                    }

                    var user = repo.GetUserById((int)id);
                    if (user == null)
                    {
                        return HttpNotFound();
                    }
                    return View(user);
                }
                else
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home");
        }

        // POST: Admins/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.Auth = null;
            if (Session["principal"] != null)
            {
                ViewBag.Auth = (User)(Session["principal"]);
                var current = new User();
                current = (User)(Session["principal"]);

                if (current.ROLE_ID == (int)(RolesEnum.admin))
                {
                    var user = repo.GetUserById((int)id);
                    var adress = user.UsersAdress;
                    db.UsersAdresses.DeleteOnSubmit(adress);
                    db.Users.DeleteOnSubmit(user);

MyGraduationProject/Views/Shared/_Layout.cshtml
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <link href='https://fonts.googleapis.com/css?family=Righteous|Russo+One|Archivo+Black|Shadows+Into+Light+Two|Audiowide|Lato&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
    <title>Michał Graczyk - Projekt Dyplomowy</title>
    <link href="~/Content/fullcalendar.print.css" media="print" rel="stylesheet" />

    <meta name="description" content="Opis w Google" />
    <meta name="keywords" content="słowa, kluczowe, wypisane, po, porzecinku" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
</head>
<body>
    <div class="wrapper">
        <div class="header">
            Internetowy system wypożyczania przedmiotów
        </div>
        <div class="navigation">
            <ol>
                <li>@Html.ActionLink("Strona Główna", "Index", "Home")</li>
                @if (ViewBag.Auth != null && ViewBag.Auth.ROLE_ID == 2)
                {
                    <li>@Html.ActionLink("Profil", "Index", "Client")</li>
                }
                else
                {
                    <li>@Html.ActionLink("O nas", "About", "Home")</li>
                }

                <li>@Html.ActionLink("Asortyment", "Assortment", "Home")</li>

                @if (ViewBag.Auth != null)
                {
                    <li>@Html.ActionLink("Wyloguj", "Logout", "Home")</li>
                }
                else
                {
                    <li>@Html.ActionLink("Zaloguj", "Login", "Home")</li>
                }

                @if (ViewBag.Auth != null && ViewBag.Auth.ROLE_ID == 1)
                {
                    <li>
                        <a href="#">Opcje</a>
                        <ul>
                            <li>@Html.ActionLink("Stwórz Użytkownika", "Create", "Admins")</li>
                            <li>@Html.ActionLink("Lista Użytkowników", "Index", "Admins")</li>
                            <li>@Html.ActionLink("Dodaj Produkt", "CreateItem", "Admins")</li>
                            <li>@Html.ActionLink("Lista Produktów", "ListOfItems", "Admins")</li>
                            <li>@Html.ActionLink("Właściwości Produktów", "ListOfProperties", "Admins")</li>
                            <li>@Html.ActionLink("Lista Zamówień", "ListOfReservations", "Admins")</li>
                        </ul>
                    </li>
                }
                else
                {
                    <li>@Html.ActionLink("Informacje", "Contact", "Home")</li>
                }

            </ol>
        </div>
            @RenderBody()   
        <div class="socialmedia">
            <div class="socCenter">
                <a href="http://facebook.com" target="_blank" class="soc">
                    <div class="fb"><i class="icon-facebook"></i></div>
                </a>

                <a href="http://youtube.com" target="_blank" class="soc">
                    <div class="yt"><i class="icon-youtube"></i></div>
                </a>

                <a href="http://twitter.com" target="_blank" class="soc">
                    <div class="tw"><i class="icon-twitter"></i></div>
                </a>
                <div style="clear:both;"></div>
            </div>
        </div>
        <div class="footer">
            <span style="color:white">Michał Graczyk - Projekt Dyplomowy &copy; 2016</span>
        </div>
    </div>
   
    @RenderSection("scripts", required: false) 
</body>
</html>